package com.codex.codexplt.bd;
// Generated 11/03/2017 08:16:33 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;

import com.codex.codexplt.vo.Dominio;

/**
 * PltDominio generated by hbm2java
 */
public class PltDominio implements java.io.Serializable, Dominio {

	private long dominioIdn;
	private String dominioNombre;
	private String dominioValor;
	private String dominioLeyenda;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;

	public PltDominio() {
	}

	public PltDominio(long dominioIdn, String dominioNombre, String dominioValor, String dominioLeyenda,
			String audiUsuario, Date audiFechModi, boolean audiSiAnul) {
		this.dominioIdn = dominioIdn;
		this.dominioNombre = dominioNombre;
		this.dominioValor = dominioValor;
		this.dominioLeyenda = dominioLeyenda;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public PltDominio(long dominioIdn, String dominioNombre, String dominioValor, String dominioLeyenda,
			String audiUsuario, Date audiFechModi, boolean audiSiAnul, String audiMotiAnul, String audiChecksum) {
		this.dominioIdn = dominioIdn;
		this.dominioNombre = dominioNombre;
		this.dominioValor = dominioValor;
		this.dominioLeyenda = dominioLeyenda;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
	}

	public long getDominioIdn() {
		return this.dominioIdn;
	}

	public void setDominioIdn(long dominioIdn) {
		this.dominioIdn = dominioIdn;
	}

	public String getDominioNombre() {
		return this.dominioNombre;
	}

	public void setDominioNombre(String dominioNombre) {
		this.dominioNombre = dominioNombre;
	}

	public String getDominioValor() {
		return this.dominioValor;
	}

	public void setDominioValor(String dominioValor) {
		this.dominioValor = dominioValor;
	}

	public String getDominioLeyenda() {
		return this.dominioLeyenda;
	}

	public void setDominioLeyenda(String dominioLeyenda) {
		this.dominioLeyenda = dominioLeyenda;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	@Override
	public String getValor() {
		return getDominioValor();
	}

	@Override
	public String getLeyenda() {

		return getDominioLeyenda();
	}

}
