package com.codex.codexplt.bd;
// Generated 11/03/2017 08:16:33 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.codex.codexplt.vo.Formulario;
import com.codex.codexplt.vo.Menu;

/**
 * PltMenu generated by hbm2java
 */
public class PltMenu implements java.io.Serializable, Menu {

	private long menuIdn;
	private PltMenu pltMenu;
	private PltFormulario pltFormulario;
	private String menuNombre;
	private short menuOrden;
	private String audiUsuario;
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;
	private Set<PltMenu> pltMenus = new HashSet<PltMenu>(0);

	public PltMenu() {
	}

	public PltMenu(long menuIdn, String menuNombre, short menuOrden, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul) {
		this.menuIdn = menuIdn;
		this.menuNombre = menuNombre;
		this.menuOrden = menuOrden;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public PltMenu(long menuIdn, PltMenu pltMenu, PltFormulario pltFormulario, String menuNombre, short menuOrden,
			String audiUsuario, Date audiFechModi, boolean audiSiAnul, String audiMotiAnul, String audiChecksum,
			Set<PltMenu> pltMenus) {
		this.menuIdn = menuIdn;
		this.pltMenu = pltMenu;
		this.pltFormulario = pltFormulario;
		this.menuNombre = menuNombre;
		this.menuOrden = menuOrden;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
		this.pltMenus = pltMenus;
	}

	public long getMenuIdn() {
		return this.menuIdn;
	}

	public void setMenuIdn(long menuIdn) {
		this.menuIdn = menuIdn;
	}

	public PltMenu getPltMenu() {
		return this.pltMenu;
	}

	public void setPltMenu(PltMenu pltMenu) {
		this.pltMenu = pltMenu;
	}

	public PltFormulario getPltFormulario() {
		return this.pltFormulario;
	}

	public void setPltFormulario(PltFormulario pltFormulario) {
		this.pltFormulario = pltFormulario;
	}

	public String getMenuNombre() {
		return this.menuNombre;
	}

	public void setMenuNombre(String menuNombre) {
		this.menuNombre = menuNombre;
	}

	public short getMenuOrden() {
		return this.menuOrden;
	}

	public void setMenuOrden(short menuOrden) {
		this.menuOrden = menuOrden;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	public Set<PltMenu> getPltMenus() {
		return this.pltMenus;
	}

	public void setPltMenus(Set<PltMenu> pltMenus) {
		this.pltMenus = pltMenus;
	}

	@Override
	public String getNombre() {
		
		return getMenuNombre();
	}

	@Override
	public Formulario getFormulario() {
		
		return getPltFormulario();
	}

	@Override
	public Menu getPadre() {
		
		return getPltMenu();
	}

}
