package com.codex.codexplt.bd;
// Generated 11/03/2017 08:16:33 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.codex.codexplt.ant.Columna;
import com.codex.codexplt.ant.Tabla;

/**
 * PltRol generated by hbm2java
 */
@Tabla
public class PltRol implements java.io.Serializable {
	
	private long rolIdn;
	@Columna(orden=1)
	private String rolNombre;
	@Columna(orden=2)
	private String rolDescripcion;
	@Columna(orden=3)
	private String audiUsuario;
	@Columna(orden=4)
	private Date audiFechModi;
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;
	private Set<PltUsuaRol> pltUsuaRols = new HashSet<PltUsuaRol>(0);
	private Set<PltPermiso> pltPermisos = new HashSet<PltPermiso>(0);

	public PltRol() {
	}

	public PltRol(long rolIdn, String rolNombre, String audiUsuario, Date audiFechModi, boolean audiSiAnul) {
		this.rolIdn = rolIdn;
		this.rolNombre = rolNombre;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public PltRol(long rolIdn, String rolNombre, String rolDescripcion, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul, String audiMotiAnul, String audiChecksum,
			Set<PltUsuaRol> pltUsuaRols, Set<PltPermiso> pltPermisos) {
		this.rolIdn = rolIdn;
		this.rolNombre = rolNombre;
		this.rolDescripcion = rolDescripcion;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
		this.pltUsuaRols = pltUsuaRols;
		this.pltPermisos = pltPermisos;
	}

	public long getRolIdn() {
		return this.rolIdn;
	}

	public void setRolIdn(long rolIdn) {
		this.rolIdn = rolIdn;
	}

	public String getRolNombre() {
		return this.rolNombre;
	}

	public void setRolNombre(String rolNombre) {
		this.rolNombre = rolNombre;
	}

	public String getRolDescripcion() {
		return this.rolDescripcion;
	}

	public void setRolDescripcion(String rolDescripcion) {
		this.rolDescripcion = rolDescripcion;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	
	public Set<PltUsuaRol> getPltUsuaRols() {
		return this.pltUsuaRols;
	}

	public void setPltUsuaRols(Set<PltUsuaRol> pltUsuaRols) {
		this.pltUsuaRols = pltUsuaRols;
	}

	public Set<PltPermiso> getPltPermisos() {
		return this.pltPermisos;
	}

	public void setPltPermisos(Set<PltPermiso> pltPermisos) {
		this.pltPermisos = pltPermisos;
	}

}
