package com.codex.codexplt.bd;
// Generated 11/03/2017 08:16:33 AM by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import com.codex.codexplt.ant.Columna;
import com.codex.codexplt.ant.Tabla;
import com.codex.codexplt.vo.Usuario;

/**
 * PltUsuario generated by hbm2java
 */
@Tabla
public class PltUsuario implements java.io.Serializable, Usuario {

	private long usuaIdn;
	@Columna(orden=1)
	private String usuaLogin;
	
	@Columna(orden=2)
	private String usuaNombre;
	
	@Columna(orden=3)
	private String usuaCorreo;
	
	@Columna(orden=4)
	private String usuaEstado;
	private short usuaInteAute;
	private String usuaClave;
	private Date usuaFechClav;
	
	@Columna(orden=5)
	private String audiUsuario;
	
	@Columna(orden=6)
	private Date audiFechModi;
	
	private boolean audiSiAnul;
	private String audiMotiAnul;
	private String audiChecksum;
	private Set<PltUsuaRol> pltUsuaRols = new HashSet<PltUsuaRol>(0);
	
	public PltUsuario() {
	}

	public PltUsuario(long usuaIdn, String usuaLogin, String usuaNombre, String usuaCorreo, String usuaEstado,
			short usuaInteAute, String usuaClave, Date usuaFechClav, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul) {
		this.usuaIdn = usuaIdn;
		this.usuaLogin = usuaLogin;
		this.usuaNombre = usuaNombre;
		this.usuaCorreo = usuaCorreo;
		this.usuaEstado = usuaEstado;
		this.usuaInteAute = usuaInteAute;
		this.usuaClave = usuaClave;
		this.usuaFechClav = usuaFechClav;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
	}

	public PltUsuario(long usuaIdn, String usuaLogin, String usuaNombre, String usuaCorreo, String usuaEstado,
			short usuaInteAute, String usuaClave, Date usuaFechClav, String audiUsuario, Date audiFechModi,
			boolean audiSiAnul, String audiMotiAnul, String audiChecksum, Set<PltUsuaRol> pltUsuaRols) {
		this.usuaIdn = usuaIdn;
		this.usuaLogin = usuaLogin;
		this.usuaNombre = usuaNombre;
		this.usuaCorreo = usuaCorreo;
		this.usuaEstado = usuaEstado;
		this.usuaInteAute = usuaInteAute;
		this.usuaClave = usuaClave;
		this.usuaFechClav = usuaFechClav;
		this.audiUsuario = audiUsuario;
		this.audiFechModi = audiFechModi;
		this.audiSiAnul = audiSiAnul;
		this.audiMotiAnul = audiMotiAnul;
		this.audiChecksum = audiChecksum;
		this.pltUsuaRols = pltUsuaRols;
		
	}

	public long getUsuaIdn() {
		return this.usuaIdn;
	}

	public void setUsuaIdn(long usuaIdn) {
		this.usuaIdn = usuaIdn;
	}

	public String getUsuaLogin() {
		return this.usuaLogin;
	}

	public void setUsuaLogin(String usuaLogin) {
		this.usuaLogin = usuaLogin;
	}

	public String getUsuaNombre() {
		return this.usuaNombre;
	}

	public void setUsuaNombre(String usuaNombre) {
		this.usuaNombre = usuaNombre;
	}

	public String getUsuaCorreo() {
		return this.usuaCorreo;
	}

	public void setUsuaCorreo(String usuaCorreo) {
		this.usuaCorreo = usuaCorreo;
	}

	public String getUsuaEstado() {
		return this.usuaEstado;
	}

	public void setUsuaEstado(String usuaEstado) {
		this.usuaEstado = usuaEstado;
	}

	public short getUsuaInteAute() {
		return this.usuaInteAute;
	}

	public void setUsuaInteAute(short usuaInteAute) {
		this.usuaInteAute = usuaInteAute;
	}

	public String getUsuaClave() {
		return this.usuaClave;
	}

	public void setUsuaClave(String usuaClave) {
		this.usuaClave = usuaClave;
	}

	public Date getUsuaFechClav() {
		return this.usuaFechClav;
	}

	public void setUsuaFechClav(Date usuaFechClav) {
		this.usuaFechClav = usuaFechClav;
	}

	public String getAudiUsuario() {
		return this.audiUsuario;
	}

	public void setAudiUsuario(String audiUsuario) {
		this.audiUsuario = audiUsuario;
	}

	public Date getAudiFechModi() {
		return this.audiFechModi;
	}

	public void setAudiFechModi(Date audiFechModi) {
		this.audiFechModi = audiFechModi;
	}

	public boolean isAudiSiAnul() {
		return this.audiSiAnul;
	}

	public void setAudiSiAnul(boolean audiSiAnul) {
		this.audiSiAnul = audiSiAnul;
	}

	public String getAudiMotiAnul() {
		return this.audiMotiAnul;
	}

	public void setAudiMotiAnul(String audiMotiAnul) {
		this.audiMotiAnul = audiMotiAnul;
	}

	public String getAudiChecksum() {
		return this.audiChecksum;
	}

	public void setAudiChecksum(String audiChecksum) {
		this.audiChecksum = audiChecksum;
	}

	public Set<PltUsuaRol> getPltUsuaRols() {
		return this.pltUsuaRols;
	}

	public void setPltUsuaRols(Set<PltUsuaRol> pltUsuaRols) {
		this.pltUsuaRols = pltUsuaRols;
	}

	@Override
	public String getLogin() {
		
		return getUsuaLogin();
	}

	

}
